docker:
  user: admin
  password: admin

gw8:
  tag: master
  image: groundworkdevelopment/gw8
  instance_name: localhost
  parent_instance_name:
  child_instance_name:
  timezone: America/Denver
  dir: gw8
